---
- name: Install LMACs shit on a machine
  hosts: all,localhost
  become: true
  vars:
    bitwarden_version: "2023.9.0"
    helm_version: "3.12.3"
    helmfile_version: "0.157.0"
  roles:
    - desktop-environment
    - desktop-networking
    - desktop-applications
    - development-utils
    - docker-host # actually podman
  tasks: []

# pipx & poetry

# name: User setup
# hosts: all,localhost
# become: true
# become_user: vagrant
# tasks:
#   - name: Install dotbot
#     pip:
#       executable: pipx
#         #extra_args: --python python3.10
#       name:
#         - dotbot
#   - name: Read-write git checkout from github
#     ansible.builtin.git:
#       repo: https://github.com/leprechaun/dotfiles.git
#       dest: /home/leprechaun/.dotfiles/
#   - name: Install dotfiles
#     command: /home/leprechaun/.local/bin/dotbot -c /home/leprechaun/.dotfiles/dotbot.yml
