---
- name: Install LMACs shit on a machine
  hosts: all
  vars:
    #                           - { role: logstash }
  roles:
    - desktop-networking
    - desktop-applications
    - development-utils
    - docker-host
  tasks:
      - name: Install packages
        apt: pkg={{item}} state=present
        with_items:
          - nmap
          - chromium-browser

      - name: Install en_CA.UTF-8 locale
        command: locale-gen en_CA.UTF-8

      - name: Update the en_CA.UTF-8 locale
        command: update-locale LANG=en_CA.UTF-8
