- name: Install desktop/graphical applications
  apt:
    install_recommends: false
    name:
      - gimp
      - gitg

- name: Install Firefox
  import_tasks: firefox.yml

- name: Install Signal
  import_tasks: signal.yml

- name: Install Zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb

- name: Install Bitwarden
  apt:
    deb: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=deb

- name: Install Vagrant
  apt:
    pkg:
      - vagrant-libvirt
