- name: Install desktop/graphical applications
  apt: pkg={{item}}
  with_items:
    - chromium-browser
    - gstreamer1.0-fluendo-mp3
    - ubuntu-restricted-extras
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
#    - pepperflashplugin-nonfree
#    - vlc
#    - gimp
#    - virtualbox
#    - openarena
#    - banshee
  tags:
    - gui

- name: Install desktop/graphical applications
  apt: pkg={{item}}
  with_items:
    - exfat-utils
    - lm-sensors
  tags:
    - cli
