- name: Install desktop/graphical applications
  apt: pkg={{item}}
  with_items:
    - chromium-browser
    - gstreamer1.0-fluendo-mp3
    - ubuntu-restricted-extras
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
    - ncmpcpp
#    - pepperflashplugin-nonfree
#    - vlc
#    - gimp
#    - virtualbox
#    - openarena
#    - banshee
  tags:
    - gui

- name: Install desktop/graphical applications
  apt: pkg={{item}}
  with_items:
    - exfat-utils
    - lm-sensors
  tags:
    - cli

- name: Add Mopidy apt key
  apt_key:
    url: https://apt.mopidy.com/mopidy.gpg
    state: present

- name: Add Mopidy Apt repo
  apt_repository:
    repo: deb http://apt.mopidy.com/ jessie main contrib non-free
    state: present

- name: Install Mopidy
  apt:
    name: mopidy
    state: present
