- name: install development related packages
  apt: pkg={{item}}
  with_items:
    - git
    - tig
    - vim
    - gitg
    - jq
    - htop
    - build-essential
    - cmake
    - pylint
    - jsonlint
    - exuberant-ctags
    - tmux

- name: Install PIP based dependencies
  pip: name={{item}}
  with_items:
    - boto3
    - awscli
