- name: Install development related packages
  apt:
    install_recommends: false
    name:
      - git
      - tig
      - build-essential
      - vim
      - jq
      - htop
      - tmux
      - python3-pip
      - awscli
      - tmux
      - bash-completion
      - pipx
      - ansible
      - shellcheck
      - libssl-dev # for probe-rs
      - libudev-dev # for probe-rs
      - libvirt-clients

- name: Install Bitwarden CLI
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/bitwarden/clients/releases/download/cli-v{{ bitwarden_version }}/bw-linux-{{ bitwarden_version }}.zip
    dest: /usr/local/bin/
    mode: 0755

# helm plugin install https://github.com/databus23/helm-diff
- name: Get Helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: /usr/local/bin/
    include: linux-amd64/helm
    extra_opts: [--strip-components=1]
    mode: 0755
    remote_src: true

- name: Get Helmfile
  unarchive:
    src: https://github.com/helmfile/helmfile/releases/download/v{{ helmfile_version }}/helmfile_{{ helmfile_version }}_linux_amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0755
    include:
      - helmfile
- name: Get Helmfile
  unarchive:
    src: https://github.com/trufflesecurity/trufflehog/releases/download/v3.67.6/trufflehog_3.67.6_linux_amd64.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0755
    include:
      - trufflehog

- name: Install AWS SSM SSH Plugin
  apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb

- name: Install Hashicorp things
  import_tasks: hashicorp.yml

- name: Install Kubescape
  get_url:
    url: https://github.com/kubescape/kubescape/releases/download/v3.0.3/kubescape-ubuntu-latest
    dest: /usr/local/bin/kubescape
    mode: 0755

- name: Install the udev rules for probe-rs
  get_url:
    url: https://probe.rs/files/69-probe-rs.rules
    dest: /etc/udev/rules.d/69-probe-rs.rules

- name: Reload udev
  command: "udevadm control --reload"

- name: Reload udev (force on connected devices)
  command: "udevadm trigger"
