- name: Install development related packages
  apt:
    install_recommends: false
    name:
      - git
      - tig
      - build-essential
      - vim
      - jq
      - htop
      - tmux
      - python3-pip
      - awscli
      - tmux
      - bash-completion
      - pipx

- name: Install Bitwarden CLI
  ansible.builtin.unarchive:
    remote_src: true
    src: https://github.com/bitwarden/clients/releases/download/cli-v2022.6.2/bw-linux-2022.6.2.zip
    dest: /usr/local/bin/
    mode: 0755
